// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;


namespace Sample.iOS
{
    public partial class NavigationSupController : UINavigationController
    {
        public NavigationSupController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();          
        }
    }
}
